apiVersion: sql.tanzu.vmware.com/v1
kind: Postgres
metadata:
  name: customer-database
spec:
  memory: 800Mi
  cpu: "0.8"
  storageClassName: default
  monitorStorageClassName: default
  storageSize: 2G
  pgConfig:
    dbname: customer-database
    username: pgadmin
    appUser: pgappuser
